manager/src/main/resources/application.conf

Data stream max size fix

---

docker-compose.yml
dummy-runtime/buid.sbt
manager/build.sbt
manager/src/main/docker/start.sh
manager/src/main/scala/io/hydrosphere/serving/manager/ManagerServices.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/ServiceManagementService.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/actors/RepositoryIndexActor.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/clouddriver/CloudDriverService.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/clouddriver/DockerComposeCloudDriverService.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/clouddriver/LocalCloudDriverService.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/envoy/XDSManagementActor.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/envoy/xds/AbstractDSActor.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/envoy/xds/ClusterDSActor.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/envoy/xds/EndpointDSActor.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/modelsource/s3/S3ModelSource.scala

#67 
- improved docker-compose file
- added special CloudDriver implementation for docker-compose

docker-compose for first start

---

manager/src/it/scala/io/hydrosphere/serving/manager/service/ModelServiceSpec.scala

Attempt to fix a docker connetction reset error.

---

Jenkinsfile
dummy-runtime/buid.sbt
manager/src/main/resources/db/migration/V1__initial.sql
manager/src/main/scala/io/hydrosphere/serving/manager/service/envoy/xds/AbstractDSActor.scala

- added docker push to DockerHub

- Renamed dummy runtime

---

manager/src/it/scala/io/hydrosphere/serving/manager/service/ApplicationServiceITSpec.scala
manager/src/main/scala/io/hydrosphere/serving/manager/controller/ApplicationController.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/ApplicationManagementService.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/ServiceManagementService.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/clouddriver/CloudDriverService.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/clouddriver/LocalCloudDriverService.scala

Create an application fix and test

---

manager/src/it/scala/io/hydrosphere/serving/manager/service/ApplicationServiceITSpec.scala
manager/src/main/resources/db/migration/V1__initial.sql
manager/src/main/scala/io/hydrosphere/serving/manager/model/CommonJsonSupport.scala
manager/src/main/scala/io/hydrosphere/serving/manager/model/ManagerJsonSupport.scala
manager/src/main/scala/io/hydrosphere/serving/manager/model/models.scala
manager/src/main/scala/io/hydrosphere/serving/manager/repository/db/ApplicationRepositoryImpl.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/ApplicationManagementService.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/envoy/EnvoyGRPCDiscoveryService.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/envoy/XDSManagementActor.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/envoy/xds/ApplicationDSActor.scala
project/Dependencies.scala

- increased servingGrpcScala version
- Added kafka streams to application

Added kafka streams to application

---

docker-compose.yml

Docker-compose startup fix

---

manager/src/main/scala/io/hydrosphere/serving/manager/ManagerBoot.scala
manager/src/main/scala/io/hydrosphere/serving/manager/ManagerServices.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/SourceManagementService.scala

Source separation.

---

manager/src/main/scala/io/hydrosphere/serving/manager/service/envoy/xds/AbstractDSActor.scala

Added stream.onError invocation after error in stream.onNext

---

manager/src/main/scala/io/hydrosphere/serving/manager/model/api/ops/TensorProtoOps.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/clouddriver/LocalCloudDriverService.scala

- added auto-pull for runtime images
- fixed bug in TensorProtoOps

auto-pull for runtime images

---

manager/src/main/scala/io/hydrosphere/serving/manager/controller/application/ApplicationController.scala
manager/src/main/scala/io/hydrosphere/serving/manager/model/api/ops/TensorProtoOps.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/ApplicationManagementService.scala
manager/src/test/scala/io/hydrosphere/serving/manager/model/api/ContractOpsSpecs.scala

Fix swagger docs.
Result used to be generated inside an array, now this behaviour is removed.

Fix input generation.

---

manager/src/main/scala/io/hydrosphere/serving/manager/service/ApplicationManagementService.scala
manager/src/test/scala/io/hydrosphere/serving/manager/model/api/ApplicationServiceSpec.scala

1. add application enrichment to post and put
2. add modelVersion to modelname

quick fix for model and runtime name

---

manager/src/main/scala/io/hydrosphere/serving/manager/controller/application/ApplicationController.scala
manager/src/main/scala/io/hydrosphere/serving/manager/controller/application/UpdateApplicationRequest.scala

Unify fields in app requests

---

manager/src/main/docker/start.sh
manager/src/main/resources/application.conf
manager/src/main/scala/io/hydrosphere/serving/manager/ManagerConfiguration.scala
manager/src/main/scala/io/hydrosphere/serving/manager/ManagerServices.scala
manager/src/main/scala/io/hydrosphere/serving/manager/controller/prometheus/PrometheusMetricsController.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/clouddriver/LocalCloudDriverService.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/metrics/ElasticSearchMetricsService.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/metrics/PrometheusMetricsService.scala
project/Dependencies.scala

- Added ElasticSearchMetricsService
- Added ElasticSearch client

Push system metrics to elasticsearch

---

build.sbt
manager/src/main/docker/start.sh
manager/src/main/resources/application.conf
manager/src/main/scala/io/hydrosphere/serving/manager/ManagerConfiguration.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/clouddriver/LocalCloudDriverService.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/metrics/ElasticSearchMetricsService.scala
project/Common.scala

- fixed: manager can't find UI in docker-compose environment
- fixed: version for containers

Metrics example

---

manager/src/main/scala/io/hydrosphere/serving/manager/controller/model/ModelController.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/model/ModelManagementService.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/model/ModelManagementServiceImpl.scala
manager/src/test/scala/io/hydrosphere/serving/manager/service/ModelManagementSpec.scala

Fix model update

---

manager/src/main/scala/io/hydrosphere/serving/manager/controller/model/ModelController.scala
manager/src/main/scala/io/hydrosphere/serving/manager/model/protocol/CompleteJsonProtocol.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/aggregated_info/AggregatedInfoUtilityService.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/aggregated_info/AggregatedInfoUtilityServiceImpl.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/aggregated_info/AggregatedModelBuild.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/aggregated_info/AggregatedModelInfo.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/aggregated_info/AggregatedModelVersion.scala
manager/src/test/scala/io/hydrosphere/serving/manager/service/AggregatedInfoServiceSpec.scala

Model version app usage

---

manager/src/main/scala/io/hydrosphere/serving/manager/service/envoy/XDSManagementActor.scala

XDS - remove prestart Await

---

manager/src/main/scala/io/hydrosphere/serving/manager/model/db/ApplicationStage.scala
manager/src/main/scala/io/hydrosphere/serving/manager/repository/db/ServiceRepositoryImpl.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/application/ApplicationManagementServiceImpl.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/service/ServiceManagementServiceImpl.scala

Application - fix service removal

---

manager/src/main/resources/db/migration/V7__pip_aware_buildscript.sql
manager/src/main/scala/io/hydrosphere/serving/manager/service/source/ModelStorageServiceImpl.scala
manager/src/main/scala/io/hydrosphere/serving/manager/service/source/storages/local/LocalModelStorage.scala

* new pip build script 
* remove saved model files on upload to avoid file overlap.

Model build improvements and fixes

---

docs/src/main/paradox/index.md
docs/src/main/paradox/overview/architecture.md
docs/src/main/paradox/overview/concepts.md

* Added info about s3, servable definition
* Changed index order

Minor changes in docs

---

jenkinsfile.groovy

Gitbook escapes _ with \ , so I've included it in the `sed` command.

Fix sed script due to Gitbook underscore escape

---

docker-compose/hydro-root-cause.service.template
helm/rootcause/templates/deployment.yaml

Fixes https://github.com/Hydrospheredata/hydro-serving/issues/358
Merge this after https://github.com/Hydrospheredata/hydro-root-cause/pull/43

Fix entrypoint arguments for rootcause

---

helm/postgresql/Chart.yaml
helm/postgresql/templates/secrets.yaml

build: postgres bump helm version

---

helm/docker-registry/Chart.yaml

build: registry bump helm version

---

helm/auto-od/Chart.yaml
helm/auto-od/README.md
helm/auto-od/templates/deployment.yaml

build: autood bump helm chart

---

helm/mongodb/Chart.yaml
helm/mongodb/templates/secrets.yaml

build: bump mongodb and helm version

---

helm/visualization/Chart.yaml

build: visualisation bump helm version

---

helm/stat/Chart.yaml

build: stat bump helm version
